[package]
name = "demo-data"
version = "0.1.0"
edition = "2021"

[workspace]
members = [
  "api",
  "macro",
]
default-members = [
    ".",
    "api",
    "macro",
]

[workspace.package]
version = "0.1.0"
edition = "2021"

[workspace.dependencies]  # Permet de définir un référentiel des versions
darling = "0.20.8"
proc-macro2 = "1.0.73"
quote = "1.0.34"
syn = "2.0.44"


[dependencies]
demo-data-api = { version = "=0.1.0", path = "api" }      # On synchronise les version avec la crate "chapeau"
demo-data-macro = { version = "=0.1.0", path = "macro" }  # On synchronise les version avec la crate "chapeau"

[features]
debug = [
  "demo-data-macro/debug",     # Permet de débugger les types de syn
]
test_fail = []
